apiVersion: nfd.k8s-sigs.io/v1alpha1
kind: NodeFeatureRule
metadata:
  name: ccnp-dp-devices
spec:
  rules:
    - name: "intel.tdx"
      labels:
        "intel.feature.node.kubernetes.io/tdx-guest": "enabled"
      matchFeatures:
        - feature: cpu.security
          matchExpressions:
            tdx.protected: {op: IsTrue}