---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: quote-server
  namespace: ccnp
  labels:
    app: quote-server
spec:
  selector:
    matchLabels:
      app: quote-server
  template:
    metadata:
      labels:
        app: quote-server
    spec:
      tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      containers:
      - name: quote-server
        image: docker.io/library/tdx-quote-server-uds:v0.1
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - name: uds-dir
            mountPath: /run/ccnp/uds
        livenessProbe:
          exec:
            command: ["/usr/bin/grpc-health-probe", "-addr=unix:/run/ccnp/uds/quote-server.sock"]
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          exec:
            command: ["/usr/bin/grpc-health-probe", "-addr=unix:/run/ccnp/uds/quote-server.sock"]
          initialDelaySeconds: 5
          periodSeconds: 10
          failureThreshold: 10
        resources:
          limits:
            tdx.intel.com/tdx-guest: 1
      volumes:
      - name: uds-dir
        hostPath:
          type: Directory
          path: /run/ccnp/uds
      nodeSelector:
        intel.feature.node.kubernetes.io/tdx-guest: "enabled"
